version: '3.8'
services:
  production:
    build:
      context: .
      target: production
    ports:
      - "80:80"
  
  development:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    
